Update mysql-store-credential

diff --git a/mysql-store-credential b/mysql-store-credential
--- a/mysql-store-credential
+++ b/mysql-store-credential
@@ -1,8 +1,16 @@
 #
-# Store user name & password in mysql client config file
+# Set user name & password in mysql client config file
 #
-USER_NAME=$1 
-ARGS="set --login-path=local --host=$(gethostip) --user=${USER_NAME} --password"
-mysql_config_editor $ARGS
+USER_NAME=$1
+MYSQL_SERVER=$2
+if [ -z "$USER_NAME" ]; then
+        echo "User name not provided. Aborting..."
+        exit 1
+fi
+if [ -z "$MYSQL_SERVER" ]; then
+        echo "Database name not provided. Aborting..."
+        exit 1
+fi
+mysql_config_editor set --login-path=local --host=${MYSQL_SERVER} --user=${USER_NAME} --password
 
 #::END::
